### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by genio** [perl-libwin32/win32-daemon#11]
Not much in the way of change since the current release of `Win32::Daemon`

* Fix the build by fixing the case sensitive Constant to constant (RT [#126272](https://rt.cpan.org/Ticket/Display.html?id=126272) and RT [#75506](https://rt.cpan.org/Ticket/Display.html?id=75506))
* Cleaned up and organized this change log
* Use Dist::Zilla to prepare the releases
* Maintain dependencies in cpanfile
* Test with appveyor
* Move Daemon.pm to its proper spot in the lib/Win32 directory
* Take Cygwin out of the supported OSes as there are many compilation errors at the moment. Please submit a PR if you are capable of fixing this!
* Document that CreateService() requires admin rights and don't hide "permission denied" error (RT [#73715](https://rt.cpan.org/Ticket/Display.html?id=73715), RT [#86501](https://rt.cpan.org/Ticket/Display.html?id=86501) and RT [#86882](https://rt.cpan.org/Ticket/Display.html?id=86882))

But the work to fix the compilation and build and the Admin Rights correction seem to me to be enough for a release.

@xenu
@jandubois 

Can we cut a release at this point?

**Comment by jandubois** [comment]
I'm travelling right now and only have a Macbook with me; so I can't build
a release on Windows at this time. If you already got co-maint from Dave,
then go ahead and make a release. Otherwise, maybe you can upload the
release to PAUSE and let me claim the file as my release?

Or send me a Dropbox link to a tarball or something? Otherwise wait for
another 2 weeks until I have access to my Windows machines again.

Cheers,
-Jan

**Comment by genio** [comment]
@jandubois When you get a chance, can you push https://github.com/perl-libwin32/win32-daemon/releases/download/v20181025/Win32-Daemon-20181025.tar.gz to pause, please? It's all ready to go.

Thanks!!

**Comment by genio** [comment]
@jandubois If you have any written consent from Dave to grant xenu and me co-maint, I can likely work to get that done without his need for any further intervention.

**Comment by jandubois** [comment]
@genio I've uploaded the release to PAUSE now and received the confirmation email.

I've received a reply from Dave saying:

> Sure, I am fine with granting permissions to somebody you recommend. Can you send email with details on what you need me to do? 

But I've been slow in responding to him with your account details, so let's give him a little more time to respond. I've also offered to take care of the permission stuff for him, but haven't heard back yet.

**Comment by genio** [comment]
Thank you! It is out there on [MetaCPAN](https://metacpan.org/pod/Win32::Daemon) and is testing well so far. I'm closing this issue out.
