### ISSUE TITLE
Undefined subroutine &Win32::Daemon::SERVICE_STOPPED

### ISSUE THREAD

**Issue by nlv02636** [perl-libwin32/win32-daemon#13]
Hi,
  I'm using Strawberry Perl  version 28, subversion 0 

When I try to run an existing working service program I get the following issues

> perl srv.pl
Windows Server 2012 R2 Datacenter (64-bit), 6.3
Win32::Daemon ver 20181025
Undefined subroutine &Win32::Daemon::SERVICE_STOPPED called at srv.pl line 40.

Same issue on Windows 10. Win32::Daemon ver 20131206 works on both perl 5.24 and 5.26 but when I try to compile 20131206 using perl 5.28 it fails:

>gmake
cp Daemon.pm blib\lib\Win32\Daemon.pm
Running Mkbootstrap for Daemon ()
"E:\nms\perl\perl\bin\perl.exe" -MExtUtils::Command -e chmod -- 644 "Daemon.bs"
"E:\nms\perl\perl\bin\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- Daemon.bs blib\arch\auto\Win32\Daemon\Daemon.b
s 644
gcc -c   -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2   -DVERSION=\"20131206\" -DXS_VERSIO
N=\"20131206\"  "-IE:\nms\perl\perl\lib\CORE"  -DPERL_NO_GET_CONTEXT CCallbackList.cpp
gcc -c   -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2   -DVERSION=\"20131206\" -DXS_VERSIO
N=\"20131206\"  "-IE:\nms\perl\perl\lib\CORE"  -DPERL_NO_GET_CONTEXT CCallbackTimer.cpp
gcc -c   -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2   -DVERSION=\"20131206\" -DXS_VERSIO
N=\"20131206\"  "-IE:\nms\perl\perl\lib\CORE"  -DPERL_NO_GET_CONTEXT CWinStation.cpp
"E:\nms\perl\perl\bin\perl.exe" -IE:\nms\perl\perl\lib -IE:\nms\perl\perl\lib "E:\NMS\perl\perl\lib\ExtUtils/xsubpp"  -t
ypemap E:\nms\perl\perl\lib\ExtUtils\typemap -typemap E:\NMS\perl\cpan\build\Win32-Daemon-20131206\typemap Daemon.xs >xs
tmp.c && "E:\nms\perl\perl\bin\perl.exe" -MExtUtils::Command -e mv -- xstmp.c Daemon.cpp
gcc -c   -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2   -DVERSION=\"20131206\" -DXS_VERSIO
N=\"20131206\"  "-IE:\nms\perl\perl\lib\CORE"  -DPERL_NO_GET_CONTEXT Daemon.cpp
In file included from Daemon.xs:53:0:
XS_Win32Perl.h:3:46: note: #pragma message: Processing XS_Win32Perl.h
 #pragma message( "Processing XS_Win32Perl.h" )
                                              ^
In file included from E:/nms/perl/c/x86_64-w64-mingw32/include/minwindef.h:163:0,
                 from E:/nms/perl/c/x86_64-w64-mingw32/include/windef.h:8,
                 from E:/nms/perl/c/x86_64-w64-mingw32/include/windows.h:69,
                 from Daemon.xs:40:
Daemon.c: In function 'void XS_Win32__Daemon_ShowService(PerlInterpreter*, CV*)':
Daemon.c:2438:31: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
In file included from E:\nms\perl\perl\lib\CORE/perl.h:5251:0,
                 from preWin32Perl.h:30,
                 from XS_Win32Perl.h:9,
                 from Daemon.xs:53:
Daemon.xs: In function 'void XS_Win32__Daemon_SetSecurity(PerlInterpreter*, CV*)':
E:\nms\perl\perl\lib\CORE/pp.h:153:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 #define POPl  ((long)SvIVx(POPs))
                                 ^
Daemon.xs:2315:35: note: in expansion of macro 'POPl'
      pSD = (SECURITY_DESCRIPTOR*) POPl;
                                   ^
In file included from E:/nms/perl/c/x86_64-w64-mingw32/include/minwindef.h:163:0,
                 from E:/nms/perl/c/x86_64-w64-mingw32/include/windef.h:8,
                 from E:/nms/perl/c/x86_64-w64-mingw32/include/windows.h:69,
                 from Daemon.xs:40:
Daemon.xs: In function 'void XS_Win32__Daemon_DebugOutputPath(PerlInterpreter*, CV*)':
Daemon.xs:2554:18: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   RETVAL = TEXT( "" );
                  ^
gcc -c   -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2   -DVERSION=\"20131206\" -DXS_VERSIO
N=\"20131206\"  "-IE:\nms\perl\perl\lib\CORE"  -DPERL_NO_GET_CONTEXT ServiceThread.cpp
"E:\nms\perl\perl\bin\perl.exe" -MExtUtils::Mksymlists \
     -e "Mksymlists('NAME'=>\"Win32::Daemon\", 'DLBASE' => 'Daemon', 'DL_FUNCS' => {  }, 'FUNCLIST' => [], 'IMPORTS' =>
{  }, 'DL_VARS' => []);"
g++ Daemon.def -o blib\arch\auto\Win32\Daemon\Daemon.xs.dll -mdll -s -L"E:\nms\perl\perl\lib\CORE" -L"E:\nms\perl\c\lib"
 CCallbackList.o CCallbackTimer.o Constant.o CWinStation.o Daemon.o ServiceThread.o   "E:\nms\perl\perl\lib\CORE\libperl
528.a" -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -
luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32 -Wl,--enable-auto-image-base
g++: error: Constant.o: No such file or directory
gmake: *** [Makefile:490: blib\arch\auto\Win32\Daemon\Daemon.xs.dll] Error 1

E:\NMS\perl\cpan\build\Win32-Daemon-20131206>

**Comment by alphacabbage1** [comment]
I had the same issue (undefined subroutines) under strawberry 5.28.1.1 with Win32::Daemon 20181025. Fixed today, via google, with:

> **cpanm** `https://github.com/perl-libwin32/win32-daemon/archive/master.zip`

The service is back up and running, thanks! 

I'm posting to flag a couple of warnings on (manual) start-up:
```
Constant subroutine SERVICE_CONTROL_USER_DEFINED redefined at C:/Strawberry/perl/site/lib/Win32/Daemon.pm line 4294967295.
Constant subroutine SERVICE_DISABLED redefined at C:/Strawberry/perl/site/lib/Win32/Daemon.pm line 4294967295.
```
... which seems to be a thing in the revised constant.cpp

[ I had no idea Daemon.pm was so large ;) ]

**Comment by xenu** [comment]
Thanks, I've removed the duplicate constants.

**Comment by xenu** [comment]
The fixed version was released on CPAN.
