### ISSUE TITLE
Win32::Daemon - Service can't be stopped or paused by menu

### ISSUE THREAD

**Issue by rtillian** [perl-libwin32/win32-daemon#14]
According to the documentation in file daemon.pm about "AcceptedControls" the recognized controls are:

    SERVICE_ACCEPT_STOP............The service accepts messages to stop.
    SERVICE_ACCEPT_PAUSE_CONTINUE..The service accepts messages to pause
                                   and continue.
    SERVICE_ACCEPT_SHUTDOWN........The service accepts messages to
                                   shutdown the system: when the OS is
                                   shutting down the service will be
                                   notified when it has accepted this
                                   control. 

And these controls are all set by default: By default all of these controls are accepted. To change this pass in a value consisting of any of these values OR'ed together.

But reality is different: after starting the service  these  topics are grayed out on the service menu. Of course you can stop the service via taskmanager but this is not the way it should work.

Solution: before you call Win32::Daemon::StartService() in **your own service-program (not in daemon.pm)** you have to call function **Win32::Daemon::AcceptedControls** by yourself in this way:

	Win32::Daemon::AcceptedControls(SERVICE_ACCEPT_STOP
	                                  | SERVICE_ACCEPT_PAUSE_CONTINUE
	                                  | SERVICE_ACCEPT_SHUTDOWN
	                                  | SERVICE_ACCEPT_PARAMCHANGE
	                                  | SERVICE_ACCEPT_NETBINDCHANGE
	);
	
	Win32::Daemon::StartService();

Doing so lets you stop, pause etc. the service in the normal way via service-menu.

This concerns perl version 5.28. In Version 5.8 (yes, I still use it at a customer site) this works without the workaround above.

Hope I could help someone. Rudolf

**Comment by rtillian** [comment]
reopend after unintentionally closing

**Comment by xenu** [comment]
Fixed by #16.
